import CacheItem from './CacheItem';
import CacheMap from './CacheMap';
import { ICacheInstance } from './CacheInstance';
import { IFlushArgs } from './interfaces';
export declare const getCachedItem: (uid: string, instance: ICacheInstance) => CacheItem;
export declare const isOnCache: (entity: any, instance: ICacheInstance) => boolean;
export declare const isOnFlushMap: (entity: any, flushMap: any) => boolean;
export declare const getItemFlushOrCached: (uid: string, flushArgs: IFlushArgs) => CacheItem;
export declare const getCacheCurrentStack: (instance: ICacheInstance) => CacheMap<CacheItem>;
export declare const ensureItem: (entity: any, flushArgs: IFlushArgs) => CacheItem;
export declare const ensureOnFlushMap: (entity: any, flushArgs: IFlushArgs) => void;
